---
server:
  port: 7001
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        metadata:
          version: v2021 # 版本号
---
server:
  port: 7002
spring:
  profiles: test
  cloud:
    nacos:
      discovery:
        metadata:
          version: v2020
